paths:
  input_csv: "Data/survey_smoke.csv"

profile: "general"

performance:
  use_pyspark: false

analytics:
  enabled: false

semantic:
  model_name: "Data/embedding_classifier_multi/encoder"
  use_cross_encoder: false

output:
  generate_sentiment: false
  generate_wordclouds: false
  generate_segmented: false
  generate_detailed_segments: false
  generate_absa: false
