DOMAIN_WHITELIST:
  - amp
  - amp7
  - amp8
  - pmo
  - prj
  - mmb
  - mwh
  - twh
  - sgm
  - spm
  - ipl
  - pdm
  - bu
  - aw
  - qs
  - wfh
  - ecc
  - ctc
  - tdw
  - bs
  - sap
  - cm
  - hrs
  - aws
  - eccs
  - ctcs
  - tdws
  - bss
  - cms
  - comms
  - desking
  - hotdesk
  - hotdesking
  - desk
  - desks
  - deskspace
  - wellbeing
  - well-being
  - workload
  - workloads
  - workhours
  - worktime
  - balfour
  - beatty
  - barhale
  - binnies
  - mott
  - macdonald
  - bentley
  - skanska
  - sweco
 
BUSINESS_MAP:
  amp8: projects
  "amp 8": projects
  amp7: projects
  "amp 7": projects
  programme: projects
  programmes: projects
  project: projects
  prj: projects
  pmo: projects
  alliance: projects
 
  line manager: management
  supervisor: management
  leadership: management
  mgr: management
  team lead: management
  lead: management
  director: management
  senior: management
  pm: management
  site manager: management
 
  deadline: workload
  deadlines: workload
  backlog: workload
  workload: workload
  pressure: workload
  capacity: workload
  resourcing: workload
  volume: workload
  target: workload
  targets: workload
  working hours: workload
  working away: workload
  work load: workload
 
  dma: operational
  site job: operational
  planned: operational
  reactive: operational
  on-site: operational
  onsite: operational
  field: operational
 
  twh: office
  hq: office
  head office: office
  desk space: office
  hotdesk: office
 
  balfour beatty: partner company
  barhale: partner company
  binnies: partner company
  mott macdonald bentley: partner company
  mmb: partner company
  mwh: partner company
  skanska: partner company
  sweco: partner company
 
  cash cars: benefits
  pay: benefits
  salary: benefits
  benefits: benefits
 
  child care: support
  family friends: support
 
  back pain: health
  chronic pain: health
 
ACCRONYM_WHITELIST:
  - amp
  - amp7
  - amp8
  - pmo
  - prj
  - mmb
  - mwh
  - twh
  - sgm
  - spm
  - ipl
  - pdm
  - bu
  - aw
  - qs
  - wfh
  - ecc
  - ctc
  - tdw
  - bs
  - sap
  - cm
  - hrs
  - aws
  - eccs
  - ctcs
  - tdws
  - bss
  - cms
 
UNIGRAM_WHITELIST:
  - amp
  - amp7
  - amp8
  - pmo
  - mmb
  - mwh
  - twh
  - wellbeing
  - wfh
 
ALWAYS_DROP_UNIGRAMS:
  - lack
  - issues
  - having
  - thing
  - things
  - really
  - very
  - quite
  - more
  - less
  - many
  - much
  - one
  - new
  - good
  - better
  - bad
  - lot
  - day
  - week
  - now
  - made
  - change
  - get
  - take
  - make
  - doing
  - able
  - still
  - just
  - bit
  - feels
 
MUST_BE_PHRASE:
  - lack
  - issues
  - having
  - feeling
  - feel
  - feels
  - seems
  - better
  - good
  - bad
  - nice
  - ok
  - fine
  - more
  - less
  - lot
  - bit
  - much
  - many
  - sometimes
  - often
  - still
  - maybe
  - really
  - just
  - get
  - take
  - try
  - want
  - allow
  - seem
  - look
  - think
  - make
 
FORCE_PHRASES:
  - line_manager
  - work_life_balance
  - annual_leave
  - mental_health
  - physical_health
  - flexible_working
  - shift_pattern
  - travel_time
  - better_communication
  - better_support
  - better_training
  - overtime_hours
  - working_hours
  - working_away
  - work_load
  - project_deadlines
  - resource_constraints
  - time_away_work
  - working_away_home
  - work_life
  - life_balance
  - desk_space
  - child_care
  - back_pain
  - partner_company
  - made_redundant
  - cost_living
  - feels_like
  - work_colleagues
  - work_home
  - one_alliance
  - family_friends
  - work_life_balance
  - emphasis_site_work
  - site_work_planning
 
MERGE_TO_CANONICAL:
  management: manager
  managers: manager
  mgr: manager
  deadline: deadlines
  deadlines: deadlines
  target: targets
  targets: targets
  shift: shifts
  shifts: shifts
  rota: rota
  rotas: rota
  salaries: salary
  bonuses: bonus
  benefit: benefits
  policies: policy
  processes: process
  sites: site
  offices: office
  communications: communication
  trainings: training
  tools: tools
  systems: system
 
ALWAYS_BLOCK:
  - behaviour
  - behaviours
  - organise
  - organised
  - organisation
  - programme
  - programmes
  - realise
  - recognise
  - colour
  - favour
  - analyse
  - labour
  - tumour
  - wellbeing
  - comms
  - desking
  - hotdesk
  - qs
  - aw
  - ecc
  - ctc
  - tdw
  - sap
  - cm
 